### ISSUE TITLE
Incorrect brute force duration on custom bf template

### ISSUE THREAD

**Issue by TadasSu** [ComThings/PandwaRF#67]
Incorrect brute force duration on custom bruteforce templates.
Shows 1min 23sec, real time about 6 minutes.

**Comment by trollwookiee** [comment]
Should have been fixed in CC1111 v1.1.4 (Rogue only) for base 2 and 4, for which BF duration is now more precise.
Base 3 still has approximate duration

**Comment by TadasSu** [comment]
not fixed.
Shows 1hour 40min, real time must be 11days!
It even shows that transmited 40 packets (in status line) but really transmits only 4 - 6.
